# Generated by Django 2.0.3 on 2019-11-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_cultpage_oneyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultpage',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrepage',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamepage',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadpage',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='natpage',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profpage',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profpage',
            name='Category',
            field=models.IntegerField(choices=[(0, 'Select:'), (1, 'Tech Fest, Tech Quiz'), (2, 'MOOC with final assessment certificate'), (3, 'Competitions conducted by Professional Societies - (IEEE, IET, ASME, SAE, NASA etc.)'), (4, 'Attending Full time Conference/Seminars /Exhibitions/Workshop/STTP conducted at IITs/NITs'), (5, 'Paper presentation/publication at IITs/NITs'), (6, 'Poster Presentation at IITs /NITs'), (7, 'Industrial Training/Internship (at least for 5 full days)'), (8, 'Industrial/Exhibition visits'), (9, 'Foreign Language Skill (TOFEL/IELTS/BEC exams etc.)')], default=0),
        ),
    ]
