# Generated by Django 2.0.3 on 2019-11-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20191125_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cult',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='entre',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='game',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='prof',
        ),
    ]
