# Generated by Django 2.0.3 on 2019-11-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20191125_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cult',
            field=models.ManyToManyField(related_name='cult', to='accounts.CultPage'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='entre',
            field=models.ManyToManyField(related_name='entre', to='accounts.EntrePage'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='game',
            field=models.ManyToManyField(related_name='game', to='accounts.GamePage'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lead',
            field=models.ManyToManyField(related_name='lead', to='accounts.LeadPage'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nat',
            field=models.ManyToManyField(related_name='nat', to='accounts.NatPage'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prof',
            field=models.ManyToManyField(related_name='prof', to='accounts.ProfPage'),
        ),
    ]
