# Generated by Django 2.0.3 on 2020-05-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20200108_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultpage',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='cult_file'),
        ),
        migrations.AlterField(
            model_name='entrepage',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='entre_file'),
        ),
        migrations.AlterField(
            model_name='gamepage',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='game_file'),
        ),
        migrations.AlterField(
            model_name='leadpage',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='lead_file'),
        ),
        migrations.AlterField(
            model_name='natpage',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='nat_file'),
        ),
        migrations.AlterField(
            model_name='profpage',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='prof_file'),
        ),
    ]
