# Generated by Django 3.0.7 on 2020-08-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20200519_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultpage',
            old_name='user3',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='entrepage',
            old_name='user5',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='gamepage',
            old_name='user6',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='leadpage',
            old_name='user1',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='natpage',
            old_name='user2',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profpage',
            old_name='user4',
            new_name='user',
        ),
    ]
